# Generated by Django 3.2.7 on 2021-10-05 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='Eps',
            fields=[
                ('id_eps', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Eps',
            },
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id_especialidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Especialidades',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('identificacion', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('apellidoPaterno', models.CharField(max_length=35)),
                ('apellidoMaterno', models.CharField(max_length=35)),
                ('nombres', models.CharField(max_length=35)),
                ('email', models.CharField(max_length=100)),
                ('contrasenia', models.CharField(max_length=30)),
                ('eps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamiento.eps')),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id_municipio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamiento.departamento')),
            ],
            options={
                'verbose_name_plural': 'Municipios',
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('identificacion', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('apellido', models.CharField(max_length=35)),
                ('nombres', models.CharField(max_length=35)),
                ('eps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamiento.eps')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamiento.especialidad')),
            ],
            options={
                'verbose_name_plural': 'Medicos',
            },
        ),
        migrations.CreateModel(
            name='CitasMedicas',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamiento.especialidad')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamiento.medico')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamiento.municipio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamiento.usuario')),
            ],
            options={
                'verbose_name_plural': 'Citas medicas',
            },
        ),
    ]
