# Generated by Django 3.2.7 on 2021-10-06 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamiento', '0002_alter_citasmedicas_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='identificacion',
            field=models.IntegerField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='identificacion',
            field=models.IntegerField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
