# Generated by Django 3.2.7 on 2021-10-06 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamiento', '0005_auto_20211006_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='identificacion',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='identificacion',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
