# Generated by Django 3.2.7 on 2021-10-07 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamiento', '0007_auto_20211006_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='identificacion',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='identificacion',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
