# Generated by Django 3.2.7 on 2021-10-25 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamiento', '0008_auto_20211006_2107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='contrasenia',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='nombres',
            new_name='username',
        ),
    ]
